Dratstat Working -Fix for audit summary legend -Added Apache Drat logo instead of just Apache -Had to comment out new repository clearing method of drat script

diff --git a/distribution/src/main/resources/bin/drat b/distribution/src/main/resources/bin/drat
--- a/distribution/src/main/resources/bin/drat
+++ b/distribution/src/main/resources/bin/drat
@@ -243,28 +243,28 @@ function reset {
 }
 
 # Clears the Solr Statistics repo for aggregating crawl stats. Expects no arguments.
-function delstats{
-    check_services_running "running"
-    check_num_args "delstats" $# 0
-    echo "This will remove any previous or current Solr DRAT stats information."
-    read -p "Do you wish to continue? [yN] " yn
-        case $yn in
-            [Yy]*)
-                echo "rm -rf $DRAT_HOME/solr/statistics/data"
-                rm -rf $DRAT_HOME/solr/statistics/data
-                echo "Please restart OODT with '\$DRAT_HOME/bin/oodt start' if you wish to run another crawl."
-            ;;
-            [Nn]*)
-                echo "Reset cancelled. Exiting..."
-                exit 0
-            ;;
-            *)
-                echo "Aborting..."
-                exit 1
-            ;;
-        esac
-
-}
+#function delstats{
+#    check_services_running "running"
+#    check_num_args "delstats" $# 0
+#    echo "This will remove any previous or current Solr DRAT stats information."
+#    read -p "Do you wish to continue? [yN] " yn
+#        case $yn in
+#            [Yy]*)
+#                echo "rm -rf $DRAT_HOME/solr/statistics/data"
+#                rm -rf $DRAT_HOME/solr/statistics/data
+#                echo "Please restart OODT with '\$DRAT_HOME/bin/oodt start' if you wish to run another crawl."
+#            ;;
+#            [Nn]*)
+#                echo "Reset cancelled. Exiting..."
+#                exit 0
+#            ;;
+#            *)
+#                echo "Aborting..."
+#                exit 1
+#            ;;
+#        esac
+#
+#}
 
 # Start parsing the arguments.
 case $1 in
